Repository basharulalammazu/Green-Tea-Coffee-Shop, pull requests merged in 2025-01, with the labels that each got.

#47 fixed admin pfp bug
  admin/add_products.php
  admin/profile.php
  admin/register.php
  components/alert.php
  image/admin/26.jpg
  image/admin/27.jpg
  image/admin/28.jpg
  image/admin/29.jpg
  image_manager.php
Labels: bug, enhancement

#48 Redesign in admin registration
  admin/admin_reg.php
  admin/admin_style.css
  admin/register.php
  admin/user_account.php
Labels: enhancement

#49 Fixed some css issues
  admin/admin_style.css
  admin/read_product.php
Labels: bug, enhancement

#50 Dashboard/Read Product now shows product image
  admin/admin_style.css
  admin/read_product.php
  image/product/13.jpg
Labels: bug, enhancement

#51 Fixed product addition redirection to the wrong page
  admin/add_products.php
  components/alert.php
  image/product/14.jpg
Labels: bug, enhancement

#52 Cart and wishlist issue solve
  view_page.php
  view_products.php
Labels: bug

#53 Messaging order by dsc
  admin/admin_message.php
Labels: bug

#54 bug fixed
  admin/components/admin_header.php
  admin/dashboard.php
  admin/register.php
  change_password.php
  checkout.php
  order.php
  style.css
  view_order.php
  view_page.php
  view_products.php
Labels: bug
